# Dev overrides for UI service.

# Cheap, simple environment for local/dev EKS testing.

replicaCount: 1

resources:
requests:
cpu: 64m
memory: 256Mi

autoscaling:
enabled: false

podDisruptionBudget:
enabled: false
