# Default values for catalog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ----------------------------------------------------------------------------
# WORKLOAD REPLICA CONFIGURATION
# ----------------------------------------------------------------------------
replicaCount: 3

# ----------------------------------------------------------------------------
# IMAGE CONFIGURATION
# ----------------------------------------------------------------------------
image:
  repository: # <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/retail-store/catalog
  pullPolicy: IfNotPresent
  tag: 

# ----------------------------------------------------------------------------
# METADATA
# ----------------------------------------------------------------------------
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

# ----------------------------------------------------------------------------
# SERVICE ACCOUNT
# ----------------------------------------------------------------------------
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# ----------------------------------------------------------------------------
# SECURITY
# ----------------------------------------------------------------------------
podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# ----------------------------------------------------------------------------
# AWS SECURITY GROUPS FOR PODS
# ----------------------------------------------------------------------------
securityGroups:
  create: false
  securityGroupIds: []

# ----------------------------------------------------------------------------
# SERVICE
# ----------------------------------------------------------------------------
service:
  type: ClusterIP
  port: 80

# ----------------------------------------------------------------------------
# RESOURCE MANAGEMENT
# ----------------------------------------------------------------------------
resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 256m
    memory: 256Mi

# ----------------------------------------------------------------------------
# AUTOSCALING - HORIZONTAL POD AUTOSCALER (HPA)
# ----------------------------------------------------------------------------
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# ----------------------------------------------------------------------------
# SCHEDULING
# ----------------------------------------------------------------------------
nodeSelector: {}

tolerations: []

affinity: {}

# ----------------------------------------------------------------------------
# TOPOLOGY SPREAD CONSTRAINTS
# ----------------------------------------------------------------------------
topologySpreadConstraints: []

# ----------------------------------------------------------------------------
# METRICS
# ----------------------------------------------------------------------------
metrics:
  enabled: true
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"

# ----------------------------------------------------------------------------
# CONFIG MAP
# ----------------------------------------------------------------------------
configMap:
  create: true
  name:

# ----------------------------------------------------------------------------
# APPLICATION CONFIGURATION
# ----------------------------------------------------------------------------
app:
  persistence:
    provider: in-memory
    endpoint: ""
    database: "catalog"

    secret:
      create: true
      name: catalog-db
      username: catalog
      password: ""

# ----------------------------------------------------------------------------
# DATABASE
# ----------------------------------------------------------------------------
mysql:
  create: false

  image:
    repository: public.ecr.aws/docker/library/mysql
    pullPolicy: IfNotPresent
    tag: "8.0"

  service:
    type: ClusterIP
    port: 3306

  podAnnotations: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  persistentVolume:
    enabled: false
    annotations: {}
    labels: {}
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    storageClass: ""

# ----------------------------------------------------------------------------
# OPEN TELEMETRY
# ----------------------------------------------------------------------------
opentelemetry:
  enabled: true
  instrumentation: "default-instrumentation"

# ----------------------------------------------------------------------------
# POD DISRUPTION BUDGET (PDB)
# ----------------------------------------------------------------------------
# Maintain minimum availability during voluntary disruptions (node drains, etc.)
podDisruptionBudget:
  enabled: true
  maxUnavailable: 1
