name: Build and Push Catalog Service to ECR

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths:
      - "src/catalog/**/*.go"
      - "src/catalog/go.mod"
      - "src/catalog/go.sum"
      - "src/catalog/Dockerfile"
      - "src/catalog/.dockerignore"
      #- ".github/workflows/build-push-catalog.yaml" # Testing only

permissions:
  id-token: write
  contents: write

jobs:
  build-and-push-catalog:
    uses: ./.github/workflows/reusable-build-push-service.yaml
    with:
      service_name: catalog
      service_dir: src/catalog
      ecr_repository: retail-store/catalog
      helm_values_file: src/catalog/chart/values.yaml
      role_to_assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-oidc-role-catalog
      aws_region: us-east-1