name: Build and Push UI Service to ECR

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths:
      - "src/ui/src/**"
      - "src/ui/Dockerfile"
      - "src/ui/pom.xml"
      - "src/ui/mvnw"
      - "src/ui/.mvn/**"
      - "src/ui/.dockerignore"
      #- ".github/workflows/build-push-ui.yaml" # Testing only

permissions:
  id-token: write
  contents: write

jobs:
  build-and-push-ui:
    uses: ./.github/workflows/reusable-build-push-service.yaml
    with:
      service_name: ui
      service_dir: src/ui
      ecr_repository: retail-store/ui
      helm_values_file: src/ui/chart/values-ui.yaml
      role_to_assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-oidc-role-ui
      aws_region: us-east-1